from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialogo(object):
    def setupUi(self, dialogo):
        dialogo.setObjectName("dialogo")
        dialogo.resize(654, 340)
        self.lcd_2 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_2.setGeometry(QtCore.QRect(190, 180, 81, 31))
        self.lcd_2.setObjectName("lcd_2")
        self.lcd_1 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_1.setGeometry(QtCore.QRect(190, 140, 81, 31))
        self.lcd_1.setObjectName("lcd_1")
        self.repartirButton = QtWidgets.QPushButton(dialogo)
        self.repartirButton.setGeometry(QtCore.QRect(280, 90, 89, 34))
        self.repartirButton.setObjectName("repartirButton")
        self.lcd_20 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_20.setGeometry(QtCore.QRect(520, 140, 81, 31))
        self.lcd_20.setObjectName("lcd_20")
        self.label_2 = QtWidgets.QLabel(dialogo)
        self.label_2.setGeometry(QtCore.QRect(50, 190, 131, 18))
        self.label_2.setObjectName("label_2")
        self.lcd_5 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_5.setGeometry(QtCore.QRect(190, 220, 81, 31))
        self.lcd_5.setObjectName("lcd_5")
        self.lcd_100 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_100.setGeometry(QtCore.QRect(520, 220, 81, 31))
        self.lcd_100.setObjectName("lcd_100")
        self.label_20 = QtWidgets.QLabel(dialogo)
        self.label_20.setGeometry(QtCore.QRect(380, 150, 131, 18))
        self.label_20.setObjectName("label_20")
        self.exitButton = QtWidgets.QPushButton(dialogo)
        self.exitButton.setGeometry(QtCore.QRect(450, 260, 89, 34))
        self.exitButton.setObjectName("exitButton")
        self.lcd_50 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_50.setGeometry(QtCore.QRect(520, 180, 81, 31))
        self.lcd_50.setObjectName("lcd_50")
        self.lcd_10 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_10.setGeometry(QtCore.QRect(190, 260, 81, 31))
        self.lcd_10.setObjectName("lcd_10")
        self.label_100 = QtWidgets.QLabel(dialogo)
        self.label_100.setGeometry(QtCore.QRect(380, 230, 131, 18))
        self.label_100.setObjectName("label_100")
        self.label_9 = QtWidgets.QLabel(dialogo)
        self.label_9.setGeometry(QtCore.QRect(50, 230, 131, 18))
        self.label_9.setObjectName("label_9")
        self.instruccionLabel = QtWidgets.QLabel(dialogo)
        self.instruccionLabel.setGeometry(QtCore.QRect(50, 50, 251, 18))
        self.instruccionLabel.setObjectName("instruccionLabel")
        self.cantidadInput = QtWidgets.QLineEdit(dialogo)
        self.cantidadInput.setGeometry(QtCore.QRect(320, 40, 281, 31))
        self.cantidadInput.onlyInt = QtGui.QIntValidator()
        self.cantidadInput.setValidator(self.cantidadInput.onlyInt)
        self.cantidadInput.setMaxLength(7)
        self.cantidadInput.setObjectName("cantidadInput")
        self.label_50 = QtWidgets.QLabel(dialogo)
        self.label_50.setGeometry(QtCore.QRect(380, 190, 131, 18))
        self.label_50.setObjectName("label_50")
        self.label_10 = QtWidgets.QLabel(dialogo)
        self.label_10.setGeometry(QtCore.QRect(50, 270, 131, 18))
        self.label_10.setObjectName("label_10")
        self.label_1 = QtWidgets.QLabel(dialogo)
        self.label_1.setGeometry(QtCore.QRect(50, 150, 121, 18))
        self.label_1.setObjectName("label_1")

        self.retranslateUi(dialogo)
        QtCore.QMetaObject.connectSlotsByName(dialogo)

    def retranslateUi(self, dialogo):
        _translate = QtCore.QCoreApplication.translate
        dialogo.setWindowTitle(_translate("dialogo", "Repartir monto en máxima cantidad de efectivo"))
        self.repartirButton.setText(_translate("dialogo", "Repartir"))
        self.label_2.setText(_translate("dialogo", "Monedas de 2 soles: "))
        self.label_20.setText(_translate("dialogo", "Billetes de 20 soles: "))
        self.exitButton.setText(_translate("dialogo", "Salir"))
        self.label_100.setText(_translate("dialogo", "Billetes de 100 soles: "))
        self.label_9.setText(_translate("dialogo", "Monedas de 5 soles: "))
        self.instruccionLabel.setText(_translate("dialogo", "Ingrese la cantidad que desea repartir:"))
        self.label_50.setText(_translate("dialogo", "Billetes de 50 soles: "))
        self.label_10.setText(_translate("dialogo", "Billetes de 10 soles: "))
        self.label_1.setText(_translate("dialogo", "Monedas de 1 sol: "))
