# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogo_repartir.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogo(object):
    def setupUi(self, dialogo):
        dialogo.setObjectName("dialogo")
        dialogo.resize(656, 340)
        self.label_50 = QtWidgets.QLabel(dialogo)
        self.label_50.setGeometry(QtCore.QRect(381, 190, 131, 18))
        self.label_50.setObjectName("label_50")
        self.cantidadInput = QtWidgets.QLineEdit(dialogo)
        self.cantidadInput.setGeometry(QtCore.QRect(321, 40, 281, 31))
        self.cantidadInput.setObjectName("cantidadInput")
        self.cantidadInput.onlyInt = QtGui.QIntValidator()
        self.cantidadInput.setValidator(self.cantidadInput.onlyInt)
        self.cantidadInput.setMaxLength(7)
        self.lcd_50 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_50.setGeometry(QtCore.QRect(521, 180, 81, 31))
        self.lcd_50.setObjectName("lcd_50")
        self.lcd_10 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_10.setGeometry(QtCore.QRect(191, 260, 81, 31))
        self.lcd_10.setObjectName("lcd_10")
        self.label_5 = QtWidgets.QLabel(dialogo)
        self.label_5.setGeometry(QtCore.QRect(51, 230, 131, 18))
        self.label_5.setObjectName("label_5")
        self.label_100 = QtWidgets.QLabel(dialogo)
        self.label_100.setGeometry(QtCore.QRect(381, 230, 131, 18))
        self.label_100.setObjectName("label_100")
        self.label_1 = QtWidgets.QLabel(dialogo)
        self.label_1.setGeometry(QtCore.QRect(51, 150, 121, 18))
        self.label_1.setObjectName("label_1")
        self.lcd_100 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_100.setGeometry(QtCore.QRect(521, 220, 81, 31))
        self.lcd_100.setObjectName("lcd_100")
        self.lcd_20 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_20.setGeometry(QtCore.QRect(521, 140, 81, 31))
        self.lcd_20.setObjectName("lcd_20")
        self.lcd_1 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_1.setGeometry(QtCore.QRect(191, 140, 81, 31))
        self.lcd_1.setObjectName("lcd_1")
        self.label_10 = QtWidgets.QLabel(dialogo)
        self.label_10.setGeometry(QtCore.QRect(51, 270, 131, 18))
        self.label_10.setObjectName("label_10")
        self.repartirButton = QtWidgets.QPushButton(dialogo)
        self.repartirButton.setGeometry(QtCore.QRect(281, 90, 89, 34))
        self.repartirButton.setObjectName("repartirButton")
        self.label_2 = QtWidgets.QLabel(dialogo)
        self.label_2.setGeometry(QtCore.QRect(51, 190, 131, 18))
        self.label_2.setObjectName("label_2")
        self.instruccionLabel = QtWidgets.QLabel(dialogo)
        self.instruccionLabel.setGeometry(QtCore.QRect(51, 50, 251, 18))
        self.instruccionLabel.setObjectName("instruccionLabel")
        self.exitButton = QtWidgets.QPushButton(dialogo)
        self.exitButton.setGeometry(QtCore.QRect(451, 260, 89, 34))
        self.exitButton.setObjectName("exitButton")
        self.label_20 = QtWidgets.QLabel(dialogo)
        self.label_20.setGeometry(QtCore.QRect(381, 150, 131, 18))
        self.label_20.setObjectName("label_20")
        self.lcd_2 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_2.setGeometry(QtCore.QRect(191, 180, 81, 31))
        self.lcd_2.setObjectName("lcd_2")
        self.lcd_5 = QtWidgets.QLCDNumber(dialogo)
        self.lcd_5.setGeometry(QtCore.QRect(191, 220, 81, 31))
        self.lcd_5.setObjectName("lcd_5")
        self.showError = QtWidgets.QLabel(dialogo)
        self.showError.setGeometry(QtCore.QRect(430, 80, 171, 20))
        self.showError.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.showError.setText("")
        self.showError.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.showError.setObjectName("showError")

        self.retranslateUi(dialogo)
        QtCore.QMetaObject.connectSlotsByName(dialogo)

    def retranslateUi(self, dialogo):
        _translate = QtCore.QCoreApplication.translate
        dialogo.setWindowTitle(_translate("dialogo", "Repartir un monto en la máxima cantidad de efectivo"))
        self.label_50.setText(_translate("dialogo", "Billetes de 50 soles: "))
        self.label_5.setText(_translate("dialogo", "Monedas de 5 soles: "))
        self.label_100.setText(_translate("dialogo", "Billetes de 100 soles: "))
        self.label_1.setText(_translate("dialogo", "Monedas de 1 sol: "))
        self.label_10.setText(_translate("dialogo", "Billetes de 10 soles: "))
        self.repartirButton.setText(_translate("dialogo", "Repartir"))
        self.label_2.setText(_translate("dialogo", "Monedas de 2 soles: "))
        self.instruccionLabel.setText(_translate("dialogo", "Ingrese la cantidad que desea repartir: S/"))
        self.exitButton.setText(_translate("dialogo", "Salir"))
        self.label_20.setText(_translate("dialogo", "Billetes de 20 soles: "))
